console.log(typeof undefined);//"undefined"
console.log(typeof null);//"object"
console.log(typeof true);//"boolean"
console.log(typeof 1);//"number"
console.log(typeof "xyz");//"string"
console.log(typeof {});//"object"